import sys
sys.stdout.reconfigure(encoding='utf-8')

import os
import json
import base64
from datetime import datetime
from database import DB_PATH
import sqlite3


# ── Default Branding ──────────────────────────────────────────
DEFAULT_BRANDING = {
    "company_name"    : "LLM Scanner",
    "primary_color"   : "#1F3864",
    "secondary_color" : "#2E75B6",
    "accent_color"    : "#C0392B",
    "success_color"   : "#27AE60",
    "warning_color"   : "#F1C40F",
    "font_name"       : "Helvetica",
    "logo_path"       : None,
    "footer_text"     : "Generated by LLM Scanner — github.com/Mahdi-EL/llm-scanner",
    "report_title"    : "AI Security Audit Report",
    "watermark"       : None,
    "show_llmscanner_badge": True
}


# ── Branding Manager ──────────────────────────────────────────
class BrandingManager:
    """
    Manages custom branding for tenant reports.
    Agency plan tenants can white-label all reports.
    """

    def __init__(self):
        self._ensure_tables()

    def _ensure_tables(self):
        """Creates branding tables."""
        conn = sqlite3.connect(DB_PATH)
        c    = conn.cursor()

        c.execute("""
            CREATE TABLE IF NOT EXISTS tenant_branding (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                tenant_id       TEXT UNIQUE NOT NULL,
                company_name    TEXT,
                primary_color   TEXT DEFAULT '#1F3864',
                secondary_color TEXT DEFAULT '#2E75B6',
                accent_color    TEXT DEFAULT '#C0392B',
                success_color   TEXT DEFAULT '#27AE60',
                warning_color   TEXT DEFAULT '#F1C40F',
                font_name       TEXT DEFAULT 'Helvetica',
                logo_base64     TEXT,
                logo_path       TEXT,
                footer_text     TEXT,
                report_title    TEXT,
                watermark       TEXT,
                show_badge      INTEGER DEFAULT 1,
                updated_at      TEXT NOT NULL
            )
        """)

        conn.commit()
        conn.close()

    def set_branding(self, tenant_id, branding_config):
        """
        Sets custom branding for a tenant.
        branding_config is a dict with branding options.
        """
        conn = sqlite3.connect(DB_PATH)
        c    = conn.cursor()

        c.execute("""
            INSERT OR REPLACE INTO tenant_branding (
                tenant_id, company_name,
                primary_color, secondary_color,
                accent_color, success_color, warning_color,
                font_name, footer_text, report_title,
                watermark, show_badge, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            tenant_id,
            branding_config.get("company_name", DEFAULT_BRANDING["company_name"]),
            branding_config.get("primary_color", DEFAULT_BRANDING["primary_color"]),
            branding_config.get("secondary_color", DEFAULT_BRANDING["secondary_color"]),
            branding_config.get("accent_color", DEFAULT_BRANDING["accent_color"]),
            branding_config.get("success_color", DEFAULT_BRANDING["success_color"]),
            branding_config.get("warning_color", DEFAULT_BRANDING["warning_color"]),
            branding_config.get("font_name", DEFAULT_BRANDING["font_name"]),
            branding_config.get("footer_text", DEFAULT_BRANDING["footer_text"]),
            branding_config.get("report_title", DEFAULT_BRANDING["report_title"]),
            branding_config.get("watermark"),
            1 if branding_config.get("show_llmscanner_badge", True) else 0,
            datetime.now().isoformat()
        ))

        conn.commit()
        conn.close()
        print(f"  Branding updated for tenant {tenant_id}")

    def get_branding(self, tenant_id):
        """
        Gets branding config for a tenant.
        Falls back to default branding if none set.
        """
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        c    = conn.cursor()

        c.execute("""
            SELECT * FROM tenant_branding WHERE tenant_id = ?
        """, (tenant_id,))

        row = c.fetchone()
        conn.close()

        if not row:
            return DEFAULT_BRANDING.copy()

        branding = dict(DEFAULT_BRANDING)
        branding.update({
            "company_name"         : row["company_name"],
            "primary_color"        : row["primary_color"],
            "secondary_color"      : row["secondary_color"],
            "accent_color"         : row["accent_color"],
            "success_color"        : row["success_color"],
            "warning_color"        : row["warning_color"],
            "font_name"            : row["font_name"],
            "footer_text"          : row["footer_text"],
            "report_title"         : row["report_title"],
            "watermark"            : row["watermark"],
            "logo_path"            : row["logo_path"],
            "show_llmscanner_badge": bool(row["show_badge"])
        })

        return branding

    def upload_logo(self, tenant_id, logo_path):
        """
        Uploads a logo image for the tenant.
        Stores as base64 in database.
        """
        if not os.path.exists(logo_path):
            print(f"Logo file not found: {logo_path}")
            return False

        with open(logo_path, "rb") as f:
            logo_bytes  = f.read()
            logo_base64 = base64.b64encode(logo_bytes).decode()

        conn = sqlite3.connect(DB_PATH)
        c    = conn.cursor()

        c.execute("""
            UPDATE tenant_branding
            SET logo_base64 = ?, logo_path = ?, updated_at = ?
            WHERE tenant_id = ?
        """, (logo_base64, logo_path, datetime.now().isoformat(), tenant_id))

        if c.rowcount == 0:
            # Create branding record first
            self.set_branding(tenant_id, {})
            c.execute("""
                UPDATE tenant_branding
                SET logo_base64 = ?, logo_path = ?
                WHERE tenant_id = ?
            """, (logo_base64, logo_path, tenant_id))

        conn.commit()
        conn.close()
        print(f"  Logo uploaded for tenant {tenant_id}")
        return True

    def reset_branding(self, tenant_id):
        """Resets tenant branding to defaults."""
        conn = sqlite3.connect(DB_PATH)
        c    = conn.cursor()

        c.execute("""
            DELETE FROM tenant_branding WHERE tenant_id = ?
        """, (tenant_id,))

        conn.commit()
        conn.close()
        print(f"  Branding reset for tenant {tenant_id}")

    def preview_branding(self, tenant_id):
        """Prints branding config preview."""
        branding = self.get_branding(tenant_id)

        print(f"\n  {'='*50}")
        print(f"  BRANDING PREVIEW — {tenant_id}")
        print(f"  {'='*50}")
        print(f"  Company Name   : {branding['company_name']}")
        print(f"  Primary Color  : {branding['primary_color']}")
        print(f"  Secondary Color: {branding['secondary_color']}")
        print(f"  Accent Color   : {branding['accent_color']}")
        print(f"  Font           : {branding['font_name']}")
        print(f"  Report Title   : {branding['report_title']}")
        print(f"  Footer Text    : {branding['footer_text']}")
        print(f"  Logo           : {'✅ Set' if branding.get('logo_path') else '❌ Not set'}")
        print(f"  Show Badge     : {'Yes' if branding['show_llmscanner_badge'] else 'No'}")
        print(f"  {'='*50}\n")


# ── Branded Report Generator ──────────────────────────────────
class BrandedReportGenerator:
    """
    Generates PDF reports with custom tenant branding.
    """

    def __init__(self, tenant_id=None, branding=None):
        self.tenant_id = tenant_id
        if branding:
            self.branding = branding
        elif tenant_id:
            manager      = BrandingManager()
            self.branding = manager.get_branding(tenant_id)
        else:
            self.branding = DEFAULT_BRANDING.copy()

    def _get_colors(self):
        """Converts hex colors to ReportLab colors."""
        from reportlab.lib import colors

        def hex_to_color(hex_str):
            return colors.HexColor(hex_str)

        return {
            "primary"  : hex_to_color(self.branding["primary_color"]),
            "secondary": hex_to_color(self.branding["secondary_color"]),
            "accent"   : hex_to_color(self.branding["accent_color"]),
            "success"  : hex_to_color(self.branding["success_color"]),
            "warning"  : hex_to_color(self.branding["warning_color"]),
        }

    def generate(
        self,
        json_path,
        output_path,
        target_name="AI Application"
    ):
        """
        Generates a branded PDF report.
        """
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer,
            Table, TableStyle, HRFlowable, PageBreak
        )
        import json

        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        summary = data["summary"]
        results = data["results"]
        total   = data["total_attacks"]
        score   = summary["security_score"]
        date    = data["scan_date"]

        # Get branding colors
        c_dict = self._get_colors()
        primary   = c_dict["primary"]
        secondary = c_dict["secondary"]
        accent    = c_dict["accent"]
        success   = c_dict["success"]
        warning   = c_dict["warning"]
        white     = colors.white

        doc   = SimpleDocTemplate(
            output_path, pagesize=A4,
            rightMargin=2*cm, leftMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm
        )
        story = []

        # ── Styles ────────────────────────────────────────────
        h1 = ParagraphStyle(
            "BH1", fontSize=18, textColor=primary,
            fontName="Helvetica-Bold",
            spaceAfter=10, spaceBefore=20
        )
        h2 = ParagraphStyle(
            "BH2", fontSize=14, textColor=secondary,
            fontName="Helvetica-Bold",
            spaceAfter=8, spaceBefore=14
        )
        body = ParagraphStyle(
            "BBody", fontSize=10, spaceAfter=6, leading=15
        )
        center = ParagraphStyle(
            "BCenter", fontSize=10, alignment=TA_CENTER
        )

        # ── Cover ─────────────────────────────────────────────
        company = self.branding.get("company_name", "LLM Scanner")
        title   = self.branding.get("report_title", "AI Security Audit Report")

        cover_data = [[
            Paragraph(
                f"🔐 {company}",
                ParagraphStyle(
                    "BCover", fontSize=22, textColor=white,
                    fontName="Helvetica-Bold", alignment=TA_CENTER
                )
            )
        ]]
        cover_table = Table(cover_data, colWidths=[17*cm])
        cover_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), primary),
            ("ROWPADDING", (0,0), (-1,-1), 28),
        ]))
        story.append(cover_table)
        story.append(Spacer(1, 0.5*cm))

        story.append(Paragraph(title, ParagraphStyle(
            "BTitle", fontSize=14, textColor=secondary,
            alignment=TA_CENTER
        )))
        story.append(Paragraph(
            f"Target : {target_name}",
            ParagraphStyle(
                "BTgt", fontSize=12, textColor=colors.gray,
                alignment=TA_CENTER
            )
        ))
        story.append(Paragraph(
            f"Date : {date}",
            ParagraphStyle(
                "BDate", fontSize=9, textColor=colors.gray,
                alignment=TA_CENTER, spaceAfter=20
            )
        ))

        # ── Score Box ──────────────────────────────────────────
        if score >= 70:
            score_color = success
            score_label = "GOOD"
        elif score >= 40:
            score_color = warning
            score_label = "MODERATE"
        else:
            score_color = accent
            score_label = "CRITICAL"

        score_data = [[
            Paragraph(f"{score}%", ParagraphStyle(
                "BScore", fontSize=52, textColor=white,
                fontName="Helvetica-Bold", alignment=TA_CENTER
            )),
            Paragraph(
                f"Security Score\n{score_label}",
                ParagraphStyle(
                    "BScoreLbl", fontSize=16, textColor=white,
                    fontName="Helvetica-Bold", alignment=TA_CENTER,
                    leading=24
                )
            )
        ]]
        score_table = Table(score_data, colWidths=[8*cm, 9*cm])
        score_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), score_color),
            ("ROWPADDING", (0,0), (-1,-1), 20),
            ("ALIGN",      (0,0), (-1,-1), "CENTER"),
            ("VALIGN",     (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(score_table)
        story.append(Spacer(1, 0.8*cm))

        # ── Summary ────────────────────────────────────────────
        story.append(Paragraph("Executive Summary", h1))
        story.append(HRFlowable(
            width="100%", thickness=2,
            color=primary, spaceAfter=10
        ))

        sev_rows = [
            ["Severity", "Count", "Percentage"],
            ["🚨 Critical", str(summary["critical"]),
             f"{round(summary['critical']/max(total,1)*100)}%"],
            ["🔴 High",     str(summary["high"]),
             f"{round(summary['high']/max(total,1)*100)}%"],
            ["⚠️ Medium",   str(summary["medium"]),
             f"{round(summary['medium']/max(total,1)*100)}%"],
            ["✅ Safe",     str(summary["safe"]),
             f"{round(summary['safe']/max(total,1)*100)}%"],
        ]

        sev_colors = [primary, accent, colors.HexColor("#E67E22"),
                      warning, success]
        sev_table  = Table(sev_rows, colWidths=[8*cm, 4*cm, 5*cm])
        style_cmds = [
            ("FONTNAME",  (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",  (0,0), (-1,-1), 10),
            ("ALIGN",     (0,0), (-1,-1), "CENTER"),
            ("ROWPADDING",(0,0), (-1,-1), 10),
            ("GRID",      (0,0), (-1,-1), 0.5, colors.white),
            ("TEXTCOLOR", (0,0), (-1,4), white),
        ]
        for i, color in enumerate(sev_colors):
            style_cmds.append(("BACKGROUND", (0,i), (-1,i), color))
        sev_table.setStyle(TableStyle(style_cmds))
        story.append(sev_table)
        story.append(Spacer(1, 0.8*cm))

        # ── Findings ───────────────────────────────────────────
        story.append(PageBreak())
        story.append(Paragraph("Vulnerability Findings", h1))
        story.append(HRFlowable(
            width="100%", thickness=2,
            color=primary, spaceAfter=10
        ))

        critical_high = [
            r for r in results
            if r["severity"] in ("CRITICAL", "HIGH")
        ][:10]

        for i, r in enumerate(critical_high):
            sev   = r["severity"]
            color = accent if sev == "CRITICAL" else \
                    colors.HexColor("#E67E22")

            hdr_data = [[
                Paragraph(
                    f"#{i+1} [{sev}] — "
                    f"{r['category'].replace('_',' ').title()}",
                    ParagraphStyle(
                        "BFH", fontSize=11, textColor=white,
                        fontName="Helvetica-Bold"
                    )
                ),
                Paragraph(
                    f"Score: {r['score']}/10",
                    ParagraphStyle(
                        "BFS", fontSize=11, textColor=white,
                        alignment=TA_CENTER
                    )
                )
            ]]
            hdr_table = Table(hdr_data, colWidths=[12*cm, 5*cm])
            hdr_table.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,-1), color),
                ("ROWPADDING", (0,0), (-1,-1), 8),
            ]))
            story.append(hdr_table)

            det_data = [
                ["Attack" , r["attack"][:120] + "..."],
                ["Reason" , r.get("reason","N/A")[:120]],
            ]
            det_table = Table(det_data, colWidths=[3*cm, 14*cm])
            det_table.setStyle(TableStyle([
                ("FONTNAME",   (0,0), (0,-1), "Helvetica-Bold"),
                ("FONTSIZE",   (0,0), (-1,-1), 9),
                ("BACKGROUND", (0,0), (0,-1),
                 colors.HexColor("#F5F5F5")),
                ("ROWPADDING", (0,0), (-1,-1), 6),
                ("GRID",       (0,0), (-1,-1), 0.3, colors.lightgrey),
            ]))
            story.append(det_table)
            story.append(Spacer(1, 0.3*cm))

        # ── Footer ─────────────────────────────────────────────
        story.append(Spacer(1, 1*cm))
        story.append(HRFlowable(
            width="100%", thickness=1,
            color=primary, spaceAfter=8
        ))

        footer_text = self.branding.get("footer_text", "")
        if self.branding.get("show_llmscanner_badge"):
            footer_text += " | Powered by LLM Scanner"

        story.append(Paragraph(
            footer_text,
            ParagraphStyle(
                "BFooter", fontSize=8, textColor=colors.gray,
                alignment=TA_CENTER
            )
        ))

        doc.build(story)
        print(f"\n  Branded report generated : {output_path}")
        return output_path


# ── Preset Themes ─────────────────────────────────────────────
PRESET_THEMES = {
    "dark_blue": {
        "company_name"  : "Security Team",
        "primary_color" : "#1F3864",
        "secondary_color": "#2E75B6",
        "accent_color"  : "#C0392B",
        "success_color" : "#27AE60",
        "warning_color" : "#F1C40F",
        "report_title"  : "AI Security Audit Report",
        "footer_text"   : "Confidential Security Report",
    },
    "corporate_red": {
        "company_name"  : "Security Team",
        "primary_color" : "#8B0000",
        "secondary_color": "#CC0000",
        "accent_color"  : "#FF4444",
        "success_color" : "#228B22",
        "warning_color" : "#FFA500",
        "report_title"  : "Cybersecurity Assessment Report",
        "footer_text"   : "Confidential — Do Not Distribute",
    },
    "modern_green": {
        "company_name"  : "Security Team",
        "primary_color" : "#1B4332",
        "secondary_color": "#2D6A4F",
        "accent_color"  : "#D62828",
        "success_color" : "#40916C",
        "warning_color" : "#F4A261",
        "report_title"  : "AI Security Assessment",
        "footer_text"   : "Generated by Security Team",
    },
    "midnight": {
        "company_name"  : "Security Team",
        "primary_color" : "#0D1B2A",
        "secondary_color": "#1B4F72",
        "accent_color"  : "#E74C3C",
        "success_color" : "#1E8449",
        "warning_color" : "#D4AC0D",
        "report_title"  : "AI Penetration Test Report",
        "footer_text"   : "Strictly Confidential",
    },
}


def apply_preset_theme(tenant_id, theme_name):
    """Applies a preset theme to a tenant."""
    if theme_name not in PRESET_THEMES:
        print(f"Unknown theme: {theme_name}")
        print(f"Available: {', '.join(PRESET_THEMES.keys())}")
        return False

    manager = BrandingManager()
    manager.set_branding(tenant_id, PRESET_THEMES[theme_name])
    print(f"  Theme '{theme_name}' applied to tenant {tenant_id}")
    return True


# ── CLI ───────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="LLM Scanner — Custom Branding"
    )
    subparsers = parser.add_subparsers(dest="command")

    # Set branding
    p_set = subparsers.add_parser("set")
    p_set.add_argument("tenant_id")
    p_set.add_argument("--company",   default="My Company")
    p_set.add_argument("--primary",   default="#1F3864")
    p_set.add_argument("--secondary", default="#2E75B6")
    p_set.add_argument("--footer",    default="Confidential Report")
    p_set.add_argument("--title",     default="AI Security Report")
    p_set.add_argument("--no-badge",  action="store_true")

    # Preview
    p_prev = subparsers.add_parser("preview")
    p_prev.add_argument("tenant_id")

    # Apply theme
    p_theme = subparsers.add_parser("theme")
    p_theme.add_argument("tenant_id")
    p_theme.add_argument("theme_name",
        choices=list(PRESET_THEMES.keys()))

    # Reset
    p_reset = subparsers.add_parser("reset")
    p_reset.add_argument("tenant_id")

    # Generate branded report
    p_gen = subparsers.add_parser("report")
    p_gen.add_argument("tenant_id")
    p_gen.add_argument("--input",  required=True)
    p_gen.add_argument("--output", default=None)
    p_gen.add_argument("--target", default="AI Application")

    # List themes
    subparsers.add_parser("themes")

    args    = parser.parse_args()
    manager = BrandingManager()

    if args.command == "set":
        manager.set_branding(args.tenant_id, {
            "company_name"         : args.company,
            "primary_color"        : args.primary,
            "secondary_color"      : args.secondary,
            "footer_text"          : args.footer,
            "report_title"         : args.title,
            "show_llmscanner_badge": not args.no_badge
        })

    elif args.command == "preview":
        manager.preview_branding(args.tenant_id)

    elif args.command == "theme":
        apply_preset_theme(args.tenant_id, args.theme_name)

    elif args.command == "reset":
        manager.reset_branding(args.tenant_id)

    elif args.command == "report":
        output = args.output or \
                 args.input.replace(".json", "_branded.pdf")
        gen = BrandedReportGenerator(tenant_id=args.tenant_id)
        gen.generate(args.input, output, args.target)

    elif args.command == "themes":
        print("\n  Available Themes :")
        for name, theme in PRESET_THEMES.items():
            print(f"\n  {name}")
            print(f"    Primary   : {theme['primary_color']}")
            print(f"    Secondary : {theme['secondary_color']}")
            print(f"    Title     : {theme['report_title']}")

    else:
        parser.print_help()
        