import sys
sys.stdout.reconfigure(encoding='utf-8')

import os
import json


# ── Translations ──────────────────────────────────────────────
TRANSLATIONS = {

    "en": {
        # Dashboard
        "dashboard"          : "Dashboard",
        "new_scan"           : "New Scan",
        "pricing"            : "Pricing",
        "total_scans"        : "Total Scans",
        "completed"          : "Completed",
        "running"            : "Running",
        "avg_security_score" : "Avg Security Score",
        "recent_scans"       : "Recent Scans",
        "target"             : "Target",
        "status"             : "Status",
        "security_score"     : "Security Score",
        "date"               : "Date",
        "action"             : "Action",
        "view_report"        : "View Report",
        "export_csv"         : "Export CSV",
        "search_placeholder" : "Search by target name...",
        "no_scans_yet"       : "No scans yet",
        "start_first_scan"   : "Start First Scan",

        # New Scan
        "configure_scan"     : "Configure and launch an AI security scan",
        "target_name"        : "Target Name",
        "target_type"        : "Target Type",
        "simulation"         : "Simulation (safe for development)",
        "custom_prompt"      : "Custom System Prompt (optional)",
        "launch_scan"        : "🚀 Launch Security Scan",
        "scan_info"          : "The scan will fire {count}+ attack prompts across 14 categories",
        "estimated_time"     : "Estimated time: 10-15 minutes",

        # Results
        "scan_in_progress"   : "Scan In Progress",
        "firing_attacks"     : "Firing {count}+ attack prompts and analyzing responses...",
        "auto_refresh"       : "Page refreshes automatically",
        "scan_failed"        : "Scan Failed",
        "scan_complete"      : "Scan Complete",
        "download_pdf"       : "Download PDF Report",
        "back_dashboard"     : "Back to Dashboard",
        "critical"           : "Critical",
        "high"               : "High",
        "medium"             : "Medium",
        "low"                : "Low",
        "safe"               : "Safe",

        # Severity
        "safe_label"         : "SAFE ✅",
        "low_label"          : "LOW 🟡",
        "medium_label"       : "MEDIUM ⚠️",
        "high_label"         : "HIGH 🔴",
        "critical_label"     : "CRITICAL 🚨",

        # Report
        "security_audit"     : "AI Security Audit Report",
        "generated_by"       : "Generated by LLM Scanner",
        "executive_summary"  : "Executive Summary",
        "vulnerability_details": "Vulnerability Details",
        "recommendations"    : "Recommendations",
        "attack_timeline"    : "Attack Timeline",
        "benchmark"          : "Industry Benchmark",
    },

    "fr": {
        # Dashboard
        "dashboard"          : "Tableau de bord",
        "new_scan"           : "Nouveau scan",
        "pricing"            : "Tarifs",
        "total_scans"        : "Scans totaux",
        "completed"          : "Terminés",
        "running"            : "En cours",
        "avg_security_score" : "Score moyen",
        "recent_scans"       : "Scans récents",
        "target"             : "Cible",
        "status"             : "Statut",
        "security_score"     : "Score de sécurité",
        "date"               : "Date",
        "action"             : "Action",
        "view_report"        : "Voir le rapport",
        "export_csv"         : "Exporter CSV",
        "search_placeholder" : "Rechercher par nom de cible...",
        "no_scans_yet"       : "Aucun scan pour le moment",
        "start_first_scan"   : "Lancer le premier scan",

        # New Scan
        "configure_scan"     : "Configurer et lancer un scan de sécurité AI",
        "target_name"        : "Nom de la cible",
        "target_type"        : "Type de cible",
        "simulation"         : "Simulation (sûr pour le développement)",
        "custom_prompt"      : "Prompt système personnalisé (optionnel)",
        "launch_scan"        : "🚀 Lancer le scan de sécurité",
        "scan_info"          : "Le scan lancera {count}+ prompts d'attaque sur 14 catégories",
        "estimated_time"     : "Durée estimée : 10-15 minutes",

        # Results
        "scan_in_progress"   : "Scan en cours",
        "firing_attacks"     : "Envoi de {count}+ prompts d'attaque...",
        "auto_refresh"       : "La page se rafraîchit automatiquement",
        "scan_failed"        : "Scan échoué",
        "scan_complete"      : "Scan terminé",
        "download_pdf"       : "Télécharger le rapport PDF",
        "back_dashboard"     : "Retour au tableau de bord",
        "critical"           : "Critique",
        "high"               : "Élevé",
        "medium"             : "Moyen",
        "low"                : "Faible",
        "safe"               : "Sûr",

        # Severity
        "safe_label"         : "SÛR ✅",
        "low_label"          : "FAIBLE 🟡",
        "medium_label"       : "MOYEN ⚠️",
        "high_label"         : "ÉLEVÉ 🔴",
        "critical_label"     : "CRITIQUE 🚨",

        # Report
        "security_audit"     : "Rapport d'audit de sécurité AI",
        "generated_by"       : "Généré par LLM Scanner",
        "executive_summary"  : "Résumé exécutif",
        "vulnerability_details": "Détails des vulnérabilités",
        "recommendations"    : "Recommandations",
        "attack_timeline"    : "Chronologie des attaques",
        "benchmark"          : "Référence industrie",
    },

    "ar": {
        # Dashboard
        "dashboard"          : "لوحة التحكم",
        "new_scan"           : "فحص جديد",
        "pricing"            : "الأسعار",
        "total_scans"        : "إجمالي الفحوصات",
        "completed"          : "مكتملة",
        "running"            : "جارية",
        "avg_security_score" : "متوسط درجة الأمان",
        "recent_scans"       : "الفحوصات الأخيرة",
        "target"             : "الهدف",
        "status"             : "الحالة",
        "security_score"     : "درجة الأمان",
        "date"               : "التاريخ",
        "action"             : "الإجراء",
        "view_report"        : "عرض التقرير",
        "export_csv"         : "تصدير CSV",
        "search_placeholder" : "البحث باسم الهدف...",
        "no_scans_yet"       : "لا توجد فحوصات بعد",
        "start_first_scan"   : "ابدأ أول فحص",

        # New Scan
        "configure_scan"     : "تكوين وإطلاق فحص أمني للذكاء الاصطناعي",
        "target_name"        : "اسم الهدف",
        "target_type"        : "نوع الهدف",
        "simulation"         : "محاكاة (آمنة للتطوير)",
        "custom_prompt"      : "موجه النظام المخصص (اختياري)",
        "launch_scan"        : "🚀 إطلاق الفحص الأمني",
        "scan_info"          : "سيطلق الفحص {count}+ موجه هجوم عبر 14 فئة",
        "estimated_time"     : "الوقت المقدر: 10-15 دقيقة",

        # Results
        "scan_in_progress"   : "الفحص جارٍ",
        "firing_attacks"     : "إطلاق {count}+ موجهات هجوم...",
        "auto_refresh"       : "الصفحة تتحدث تلقائياً",
        "scan_failed"        : "فشل الفحص",
        "scan_complete"      : "اكتمل الفحص",
        "download_pdf"       : "تحميل تقرير PDF",
        "back_dashboard"     : "العودة للوحة التحكم",
        "critical"           : "حرج",
        "high"               : "عالٍ",
        "medium"             : "متوسط",
        "low"                : "منخفض",
        "safe"               : "آمن",

        # Severity
        "safe_label"         : "آمن ✅",
        "low_label"          : "منخفض 🟡",
        "medium_label"       : "متوسط ⚠️",
        "high_label"         : "عالٍ 🔴",
        "critical_label"     : "حرج 🚨",

        # Report
        "security_audit"     : "تقرير تدقيق أمني للذكاء الاصطناعي",
        "generated_by"       : "تم إنشاؤه بواسطة LLM Scanner",
        "executive_summary"  : "الملخص التنفيذي",
        "vulnerability_details": "تفاصيل الثغرات",
        "recommendations"    : "التوصيات",
        "attack_timeline"    : "الجدول الزمني للهجمات",
        "benchmark"          : "معيار الصناعة",
    },

    "es": {
        "dashboard"          : "Panel de control",
        "new_scan"           : "Nuevo escaneo",
        "pricing"            : "Precios",
        "total_scans"        : "Escaneos totales",
        "completed"          : "Completados",
        "running"            : "En ejecución",
        "avg_security_score" : "Puntuación promedio",
        "recent_scans"       : "Escaneos recientes",
        "target"             : "Objetivo",
        "status"             : "Estado",
        "security_score"     : "Puntuación de seguridad",
        "date"               : "Fecha",
        "action"             : "Acción",
        "view_report"        : "Ver informe",
        "export_csv"         : "Exportar CSV",
        "search_placeholder" : "Buscar por nombre de objetivo...",
        "no_scans_yet"       : "Sin escaneos todavía",
        "start_first_scan"   : "Iniciar primer escaneo",
        "configure_scan"     : "Configurar y lanzar un escaneo de seguridad AI",
        "target_name"        : "Nombre del objetivo",
        "target_type"        : "Tipo de objetivo",
        "simulation"         : "Simulación (seguro para desarrollo)",
        "custom_prompt"      : "Prompt del sistema personalizado (opcional)",
        "launch_scan"        : "🚀 Lanzar escaneo de seguridad",
        "scan_info"          : "El escaneo disparará {count}+ prompts de ataque",
        "estimated_time"     : "Tiempo estimado: 10-15 minutos",
        "scan_in_progress"   : "Escaneo en progreso",
        "firing_attacks"     : "Disparando {count}+ prompts de ataque...",
        "auto_refresh"       : "La página se actualiza automáticamente",
        "scan_failed"        : "Escaneo fallido",
        "scan_complete"      : "Escaneo completo",
        "download_pdf"       : "Descargar informe PDF",
        "back_dashboard"     : "Volver al panel",
        "critical"           : "Crítico",
        "high"               : "Alto",
        "medium"             : "Medio",
        "low"                : "Bajo",
        "safe"               : "Seguro",
        "safe_label"         : "SEGURO ✅",
        "low_label"          : "BAJO 🟡",
        "medium_label"       : "MEDIO ⚠️",
        "high_label"         : "ALTO 🔴",
        "critical_label"     : "CRÍTICO 🚨",
        "security_audit"     : "Informe de auditoría de seguridad AI",
        "generated_by"       : "Generado por LLM Scanner",
        "executive_summary"  : "Resumen ejecutivo",
        "vulnerability_details": "Detalles de vulnerabilidades",
        "recommendations"    : "Recomendaciones",
        "attack_timeline"    : "Línea de tiempo de ataques",
        "benchmark"          : "Referencia de la industria",
    },

    "de": {
        "dashboard"          : "Dashboard",
        "new_scan"           : "Neuer Scan",
        "pricing"            : "Preise",
        "total_scans"        : "Gesamte Scans",
        "completed"          : "Abgeschlossen",
        "running"            : "Laufend",
        "avg_security_score" : "Durchschnittliche Sicherheit",
        "recent_scans"       : "Letzte Scans",
        "target"             : "Ziel",
        "status"             : "Status",
        "security_score"     : "Sicherheitsbewertung",
        "date"               : "Datum",
        "action"             : "Aktion",
        "view_report"        : "Bericht anzeigen",
        "export_csv"         : "CSV exportieren",
        "search_placeholder" : "Nach Zielname suchen...",
        "no_scans_yet"       : "Noch keine Scans",
        "start_first_scan"   : "Ersten Scan starten",
        "configure_scan"     : "KI-Sicherheitsscan konfigurieren",
        "target_name"        : "Zielname",
        "target_type"        : "Zieltyp",
        "simulation"         : "Simulation (sicher für Entwicklung)",
        "custom_prompt"      : "Benutzerdefinierter System-Prompt (optional)",
        "launch_scan"        : "🚀 Sicherheitsscan starten",
        "scan_info"          : "Der Scan wird {count}+ Angriffs-Prompts abfeuern",
        "estimated_time"     : "Geschätzte Zeit: 10-15 Minuten",
        "scan_in_progress"   : "Scan läuft",
        "firing_attacks"     : "{count}+ Angriffs-Prompts werden gesendet...",
        "auto_refresh"       : "Seite wird automatisch aktualisiert",
        "scan_failed"        : "Scan fehlgeschlagen",
        "scan_complete"      : "Scan abgeschlossen",
        "download_pdf"       : "PDF-Bericht herunterladen",
        "back_dashboard"     : "Zurück zum Dashboard",
        "critical"           : "Kritisch",
        "high"               : "Hoch",
        "medium"             : "Mittel",
        "low"                : "Niedrig",
        "safe"               : "Sicher",
        "safe_label"         : "SICHER ✅",
        "low_label"          : "NIEDRIG 🟡",
        "medium_label"       : "MITTEL ⚠️",
        "high_label"         : "HOCH 🔴",
        "critical_label"     : "KRITISCH 🚨",
        "security_audit"     : "KI-Sicherheitsprüfungsbericht",
        "generated_by"       : "Erstellt von LLM Scanner",
        "executive_summary"  : "Zusammenfassung",
        "vulnerability_details": "Sicherheitslücken Details",
        "recommendations"    : "Empfehlungen",
        "attack_timeline"    : "Angriffs-Zeitlinie",
        "benchmark"          : "Branchenvergleich",
    }
}

SUPPORTED_LANGUAGES = list(TRANSLATIONS.keys())


# ── Translator ────────────────────────────────────────────────
class Translator:
    """
    Translates UI strings and report content.
    """

    def __init__(self, language="en"):
        self.language = language if language in TRANSLATIONS else "en"
        self.strings  = TRANSLATIONS[self.language]
        self.fallback = TRANSLATIONS["en"]

    def t(self, key, **kwargs):
        """
        Translates a key to the current language.
        Falls back to English if key not found.
        """
        text = self.strings.get(key) or self.fallback.get(key, key)
        if kwargs:
            try:
                text = text.format(**kwargs)
            except:
                pass
        return text

    def set_language(self, language):
        """Changes the current language."""
        if language in TRANSLATIONS:
            self.language = language
            self.strings  = TRANSLATIONS[language]
        else:
            print(f"Language '{language}' not supported.")
            print(f"Supported : {', '.join(SUPPORTED_LANGUAGES)}")

    def get_all_languages(self):
        """Returns list of supported languages."""
        return SUPPORTED_LANGUAGES

    def translate_report_labels(self, scan_data):
        """
        Translates all severity labels in scan data.
        Useful for generating reports in different languages.
        """
        translated = scan_data.copy()

        severity_map = {
            "SAFE"    : self.t("safe_label"),
            "LOW"     : self.t("low_label"),
            "MEDIUM"  : self.t("medium_label"),
            "HIGH"    : self.t("high_label"),
            "CRITICAL": self.t("critical_label")
        }

        if "results" in translated:
            for r in translated["results"]:
                r["severity_label"] = severity_map.get(
                    r["severity"], r["severity"]
                )

        return translated


# ── Language Detector ─────────────────────────────────────────
class LanguageDetector:
    """
    Detects the language of a text string.
    Simple heuristic based on character sets.
    """

    @staticmethod
    def detect(text):
        """
        Detects language from character patterns.
        Returns language code.
        """
        if not text:
            return "en"

        # Arabic characters
        arabic_chars = sum(1 for c in text if '\u0600' <= c <= '\u06FF')
        if arabic_chars > len(text) * 0.3:
            return "ar"

        # German specific characters
        german_chars = sum(1 for c in text if c in "äöüÄÖÜß")
        if german_chars > 2:
            return "de"

        # Spanish specific characters
        spanish_chars = sum(1 for c in text if c in "áéíóúñÁÉÍÓÚÑ¿¡")
        if spanish_chars > 2:
            return "es"

        # French specific characters
        french_chars = sum(1 for c in text if c in "àâçéèêëîïôùûüÿÀÂÇÉÈÊËÎÏÔÙÛÜŸ")
        if french_chars > 2:
            return "fr"

        return "en"


# ── Multilingual Report ───────────────────────────────────────
def generate_multilingual_summary(scan_data, languages=None):
    """
    Generates report summaries in multiple languages.
    """
    if not languages:
        languages = ["en", "fr", "ar", "es", "de"]

    summaries = {}
    summary   = scan_data["summary"]

    for lang in languages:
        t = Translator(lang)
        summaries[lang] = {
            "security_score"    : summary["security_score"],
            "score_label"       : t.t("security_score"),
            "critical_label"    : t.t("critical"),
            "high_label"        : t.t("high"),
            "medium_label"      : t.t("medium"),
            "safe_label"        : t.t("safe"),
            "critical_count"    : summary["critical"],
            "high_count"        : summary["high"],
            "medium_count"      : summary["medium"],
            "safe_count"        : summary["safe"],
            "audit_title"       : t.t("security_audit"),
            "generated_by"      : t.t("generated_by"),
        }

    return summaries


# ── Save Language Preference ──────────────────────────────────
def save_language_preference(language, path="results/preferences.json"):
    """Saves user language preference."""
    os.makedirs("results", exist_ok=True)

    prefs = {}
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            try:
                prefs = json.load(f)
            except:
                prefs = {}

    prefs["language"] = language

    with open(path, "w", encoding="utf-8") as f:
        json.dump(prefs, f, indent=2)


def load_language_preference(path="results/preferences.json"):
    """Loads user language preference."""
    if not os.path.exists(path):
        return "en"

    with open(path, "r", encoding="utf-8") as f:
        try:
            prefs = json.load(f)
            return prefs.get("language", "en")
        except:
            return "en"


# ── CLI ───────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys

    print("LLM Scanner — Internationalization Module")
    print("=" * 45)
    print(f"Supported languages : {', '.join(SUPPORTED_LANGUAGES)}")
    print()

    if len(sys.argv) > 1:
        lang = sys.argv[1]
        t    = Translator(lang)

        print(f"Language : {lang}")
        print()
        print(f"  Dashboard    : {t.t('dashboard')}")
        print(f"  New Scan     : {t.t('new_scan')}")
        print(f"  Security     : {t.t('security_score')}")
        print(f"  Critical     : {t.t('critical_label')}")
        print(f"  Safe         : {t.t('safe_label')}")
        print(f"  Launch Scan  : {t.t('launch_scan')}")

    else:
        # Demo all languages
        demo_key = "security_audit"
        for lang in SUPPORTED_LANGUAGES:
            t = Translator(lang)
            print(f"  [{lang}] {t.t(demo_key)}")
            